### PR TITLE
Fix read preference using pymongo 3+

### PR DESCRIPTION
**Pull request by luiscoms**

### CODE REVIEW

**Comment by luiscoms** [comment]
@dcrosta Did you like this PR?

**Comment by luiscoms** [comment]
Hi, did you saw my changes?

**Comment by luiscoms** [comment]
Any questions about this PR?

**Comment by computist** [comment]
This doesn't fix the read preference provided in URL.

**Comment by dcrosta** [comment]
Please see the announcement about Flask-PyMongo 2.0 in #110 -- I believe that that work will obviate the fix here, and will simplify future maintenance of Flask-PyMongo, as you'll just use a URI or keyword arguments to configure PyMongo, without having to have the strange layer in between from Flask-PyMongo. 

I'm going to close this to keep things tidy, but thanks for the contribution nonetheless!

**Pull request closed without merging**
