### PR TITLE
remove auto_start_request parameter

### PR DESCRIPTION
**Pull request by ch3n2k**

### CODE REVIEW

**Comment by dcrosta** [comment]
What problem is this trying to fix -- PyMongo 3.x compatibility?

**Comment by ch3n2k** [comment]
yes, it's for pymongo 3.0 compatibility.

**Comment by dcrosta** [comment]
Got it.

Flask-PyMongo is not (yet?) PyMongo 3.x compatible. I've released 0.3.1 today which locks the requirements back to the 2.x series of PyMongo, but if you need 3.0, that won't help you. As time permits (or as people submit patches that maintain 2.x and add 3.x compatibility) I'll eventually cut a release that works with 3.x, too.

**Comment by nicolaiarocci** [comment]
FYI by accepting this PR you would make Flask-PyMongo compatibile PyMongo 3.0. As far as I can tell, PyM3 is backward compatible except for this nuisance (they deprecated a lot of things though, although according to their own word the old API will be supported *at least* until 4th generation drivers). 

My Flask-PyMongo clone, which has this line removed, runs 561 tests on MongoDB 3.0 w/PyMongo 3.0.1. However, being Flask-PyMongo requirements pinned to PyMongo 2.x, I cannot release  a PyMongo 3.0 compatible [Eve](http://python-eve.org) package.

**Comment by markunsworth** [comment]
Maybe this should be superceeded by #63

**Pull request closed without merging**
