### PR TITLE
Fix lifetime argument bug

### PR DESCRIPTION
**Pull request by joackobengochea**
Fixes issue #133

### CODE REVIEW

**Comment by dcrosta** [comment]
Can you show code that reproduces the error here? The description in #133 doesn't explain how or why that `lifetime` argument is being used. (It doesn't appear within flask-pymongo code at all)

**Comment by joackobengochea** [comment]
Sorry, looking a bit deeper we found out it's a bug in pymongo 3.9, I'll make a PR there

**Comment by joackobengochea** [comment]
https://github.com/mongodb/mongo-python-driver/pull/423

**Comment by 7i11** [comment]
to clarify, in the mongodb driver, a tag(3.9.0) was pushed where the lifetime is removed, but in the `srv_resolver`,this kwarg(lifetime) is still passed, so, if you use a connection string `mongodb+srv://`, use this `srv_resolver` which ends in an exception.
[tag commit here](https://github.com/mongodb/mongo-python-driver/commit/62400e548db8e02e82afa77b9014d21e47ed2f7c)
[here, the file that need to be changed](https://github.com/mongodb/mongo-python-driver/blob/e152e9eafa3c3e84f6e47159a148f70e0fb9508a/pymongo/srv_resolver.py#L57)

**Comment by dcrosta** [comment]
OK -- that seems like it's on the MongoDB folks to fix. If you think that there's more we should do here, please re-open this PR or let me know, but for now I'm closing this.

**Comment by Nerotagachi** [comment]
This issue still exists for me, I still get the error:
` db = MongoClient('mongodb+srv://<user>:<pw>kicapstone.14opf.mongodb.net/').capstone
> pymongo.errors.ConfigurationError: query() got an unexpected keyword argument 'lifetime'
`

I tried using the SRVResolver as mentioned by 7i11, which just gives me another error:
`db = MongoClient(SRVResolver.resolve('mongodb+srv://<user>:<pw>kicapstone.14opf.mongodb.net/')).capstone

dns.resolver.NXDOMAIN: None of DNS query names exist: mongodb+srv://kicapstoneuser:jung\@kicapstone.14opf.mongodb.net/., mongodb+srv://kicapstoneuser:jung\@kicapstone.14opf.mongodb.net/.home.
`

Does anyone have any idea how to solve this?

**Comment by Nerotagachi** [comment]
> 
> 
> This issue still exists for me, I still get the error:
> 
> Trying to connect
> db = MongoClient('mongodb+srv://:kicapstone.14opf.mongodb.net/').capstone
> 
> Gives me
> pymongo.errors.ConfigurationError: query() got an unexpected keyword argument 'lifetime'
> 
> I tried using the SRVResolver as mentioned by 7i11, which just gives me another error:
> db = MongoClient(SRVResolver.resolve('mongodb+srv://:kicapstone.14opf.mongodb.net/')).capstone
> 
> Gives me
> dns.resolver.NXDOMAIN: None of DNS query names exist:
> mongodb+srv://user:[pw@kicapstone.14opf.mongodb.net](mailto:pw@kicapstone.14opf.mongodb.net)/.,
> mongodb+srv://user:[pw@kicapstone.14opf.mongodb.net](mailto:pw@kicapstone.14opf.mongodb.net)/.home.
> 
> Does anyone have any idea how to solve this?

Actually, moving through the other issues linked to this, I was able to fix the problem. The problem was with dnspython, as I had installed dnspython 1.15. Version 1.16 solved the problem.

**Pull request closed without merging**
