### PR TITLE
Function to jsonify BSON objects

### LINKED ISSUE #62: jsonify compatibility
I've been playing around with Flask and MongoDB today and really like them. Thanks very much for making integrating Flask with PyMongo easier.

I'm really surprised at how hard it is to return JSON from a view method, considering that's the first thing I tried and really only thing I want to do for this project. If this is integrating PyMongo and Flask, shouldn't there be an equivalent to `flask.jsonify()` that works with BSON?

As you probably know, this won't work because jsonify can't deal with ObjectId:

``` python
@app.route('/search/<query>')
def search(query):
    events = mongo.db.contributions.find({
        '_user_lower' : query.lower()
    })
    events = { 'events': list(events) }
    return jsonify(**events)
```

[Akhenakh's awesome gist](https://gist.github.com/akhenakh/2954605) is working for me right now, but it seems like pymongo should offer this.

### PR DESCRIPTION
**Pull request by Dannnno**
- Add function to jsonify BSON objects
- Add test

closes #62

### CODE REVIEW

**Comment by dcrosta** [comment]
I don't think we want to be dumping to JSON, parsing from JSON, then dumping again. @ajdavis do you know of anything better to do here?

I think at worst we can use the JSON string returned by `json_utils` and create a Flask response out of that directly. Flask's [jsonify](https://github.com/pallets/flask/blob/9b734d1436ebcfb4a1a3973221b94693f9e8c1cf/flask/json.py#L273-L276) doesn't do a whole lot more than that anyway).

**Comment by ajdavis** [comment]
I don't understand the purpose of the BSON-encoding step at all. If you look at [the json_util documentation](http://api.mongodb.com/python/current/api/bson/json_util.html) it shows:

```
>>> from bson import Binary, Code
>>> from bson.json_util import dumps
>>> dumps([{'foo': [1, 2]},
...        {'bar': {'hello': 'world'}},
...        {'code': Code("function x() { return 1; }", {})},
...        {'bin': Binary(b"\x01\x02\x03\x04")}])
'[{"foo": [1, 2]}, {"bar": {"hello": "world"}}, {"code": {"$code": "function x() { return 1; }", "$scope": {}}}, {"bin": {"$binary": "AQIDBA==", "$type": "00"}}]'
```

So I think that calling json_util.dumps directly on the input ``obj`` creates the string you want. The only additional work that Flask's jsonify does is apply some styling defaults and wrap it in a Response, you could do that in flask_pymongo.jsonify, too.

**Comment by dcrosta** [comment]
Yeah, that's kind of what I thought as well. Leaving this for 2.0, in any case.

**Comment by dcrosta** [comment]
Closing in favor of #122

**Pull request closed without merging**
