### PR TITLE
Delete __init__.py in tests directory

### PR DESCRIPTION
**Pull request by ropez**
When trying to install this module in a global namespace, 'tests' is installed as a separate module that conflicts with other packages (if they have the same problem).

There are different ways to avoid this, but I'm trying the easy approach, and sending a pull request to see if the tests will still run in travis.

### CODE REVIEW

**Comment by ropez** [comment]
Tests passed in py3, but failed in py2

**Comment by dcrosta** [comment]
Probably makes sense to move the test package inside flask_pymongo

**Comment by ropez** [comment]
It is an alternative,

see https://pytest.org/latest/goodpractises.html

**Comment by ranman** [comment]
I've tested and I'm ok to merge this? 48 hours to lodge any objections?

**Pull request merged**
